<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    public function toJson($options = 0)
    {
        $this->role;
        return parent::toJson($options); // TODO: Change the autogenerated stub
    }

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',

    ];

    public function role () {
        return $this->belongsTo(Role::class);
    }

    public function news () {
        return $this->hasMany(News::class);
    }


    /**
     * The attributes that should be cast to native types.
     *
     * @param string $role
     * @return boolean
     */

    public function hasRole (string $role) {
        return $this->role->name == $role;
    }
}
